### ISSUE TITLE
torchvision is a dependency

### ISSUE THREAD

**Issue by bthirion** [nicolassalvy/EvaGeM#1]
At least it is required in the tutorial. Add it to the requirements ?

**Comment by nicolassalvy** [comment]
The readme has been updated with:

PyTorch is needed for the tutorial (both torch and torchvision) and is not covered by the dependencies, since the PyTorch version needed is dependent on your OS and device. To install PyTorch, use the command corresponding to your configuration from the [PyTorch website](https://pytorch.org/get-started/locally/).

The command on the PyTorch website installs both torch and torchvision.
